name: Deploy Rspress to GitHub Pages (2024 Optimized)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true  # 避免部署冲突[2](@ref)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: dist  # 环境变量统一管理路径[5](@ref)

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - uses: pnpm/action-setup@v3
        with:
          version: 8 # 您可以根据需要调整 pnpm 版本

      - run: pnpm install

      - run: pnpm run build
        env:
          NODE_ENV: production  # 显式声明构建环境[6](@ref)

      - name: Verify build output
        run: ls -R ${{ env.BUILD_DIR }}  # 输出目录验证[2](@ref)

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v2  # 最新稳定版部署 Action
        id: deployment